---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[moombot]
    attributes:
      moombot:
        name: moombot-dev
