---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  attributes:
    moombot:
      loggers:
        level: debug
        first_level: debug

platforms:
  - name: debian-6
  - name: debian-7
  - name: debian-8
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5
  - name: centos-6
  - name: centos-7
    driver_config:
      dockerfile: test/dockerfiles/centos7
      privileged: true
      run_command: /usr/sbin/init
      private_key:
      public_key:

suites:
  - name: moombot
    run_list:
      - recipe[moombot]
    attributes:
      moombot:
        name: moombot-dev
  - name: moombot-plugin-lwrp
    run_list:
      - recipe[moombot]
      - recipe[devbot::delete_plugin2]
    attributes:
      moombot:
        name: moombot-dev
        plugins:
          moombot: [ping]
          devbot: [plugin1, plugin2]
  - name: moombot-plugin-config
    run_list:
      - recipe[moombot]
      - recipe[devbot]
    attributes:
      moombot:
        name: moombot-dev
        plugins:
          moombot: [ping]
          devbot: [say]
        plugin_say:
          msg: Hello H4x0R!!!
