---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  chef_license: accept
  attributes:
    moombot:
      loggers:
        level: debug
        first_level: debug

verifier:
  name: inspec

platforms:
  - name: debian-8
  - name: debian-9
  - name: debian-10
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04

suites:
  - name: moombot
    run_list:
      - recipe[apt]
      - recipe[moombot]
    attributes:
      moombot:
        name: moombot-dev
  - name: moombot-plugin-lwrp
    run_list:
      - recipe[apt]
      - recipe[moombot]
      - recipe[devbot::delete_plugin2]
    attributes:
      moombot:
        name: moombot-dev
        plugins:
          moombot: [ping]
          devbot: [plugin1, plugin2]
  - name: moombot-plugin-config
    run_list:
      - recipe[apt]
      - recipe[moombot]
      - recipe[devbot]
    attributes:
      moombot:
        name: moombot-dev
        plugins:
          moombot: [ping]
          devbot: [say]
        plugin_say:
          msg: Hello H4x0R!!!
